### ISSUE TITLE
Maven artifact 

### ISSUE THREAD

**Issue by glaplace** [manticore-projects/H2MigrationTool#19]
Hello,

What is the right information to use H2 Migration Tool as a maven dependency?

The pom.xml contains H2MigrationTool as artifactId or the artifactId is h2migrationtool on the repositories.
Local gradel build provide : H2MigrationTool-1.6-SNAPSHOT.jar and local maven build h2migrationtool-1.4.0-SNAPSHOT.jar

I didn't find version 1.5 on the repositories.

I checked on the following repositories :

- https://s01.oss.sonatype.org/content/repositories/snapshots/com/manticore-projects/tools/h2migrationtool
- https://central.sonatype.com/artifact/com.manticore-projects.tools/h2migrationtool

thanks in advance

**Comment by manticore-projects** [comment]
Sorry for this confusion, I really don't use Maven directly but prefer Gradle a lot.

1) The Artifact Name must be lower case only (since the GitHub Maven repository gets confused with mixed spelling, which is a shame)
2) Latest available SNAPSHOT is 1.6

This may be helpful: https://manticore-projects.com/H2MigrationTool/usage.html#maven-artifacts
